from backend.routes.authentication import authentication_api
from backend.routes.callback import callback_api
from backend.routes.executions import executions_api
from backend.routes.exercises import exercises_api
from backend.routes.comments import comments_api
from backend.routes.cache import cache_api
from backend.routes.notifications import notifications_api
from backend.routes.stream import stream_api
from backend.routes.questionnaires import questionnaires_api
from backend.routes.statics import statics_api
from backend.routes.setup import setup_api
from backend.routes.users import users_api
from backend.routes.pages import pages_api
