publishDir: 'public/participant'

ignoreFiles:
    - \.png$
    - \.jpg$
    - \.pdf$
    - \.svg$

module:
    mounts:
        - source: 'content/'
          target: 'static/res'
          excludeFiles: '*'
        - source: '_apps/'
          target: 'static/_apps'
          excludeFiles: '*'
